language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
sudo: false
env:
 global:
   - PACKAGE=vhd-format
   - PINS="vhd-format:. vhd-format-lwt:."
 matrix:
   - DISTRO=debian-stable OCAML_VERSION=4.03
   - DISTRO=ubuntu OCAML_VERSION=4.04
   - DISTRO=debian-stable OCAML_VERSION=4.05
   - DISTRO=alpine OCAML_VERSION=4.07
