language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
sudo: false
env:
 global:
   - PACKAGE="vhd-format"
 matrix:
   - DISTRO=debian-stable OCAML_VERSION=4.03
   - DISTRO=ubuntu-16.04 OCAML_VERSION=4.03
   - DISTRO=alpine OCAML_VERSION=4.03
